apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-giropopssenhas
  labels:
    app: {{ .Release.Name }}-giropopssenhas
spec:
  replicas: {{ .Values.replicas.min }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-giropopssenhas
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-giropopssenhas
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
          name: giropops-senhas
        env:
        - name: REDIS_HOST
          value: redis-service
        resources:
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"
          limits:
            cpu: "{{ .Values.resources.limits.cpu }}"
            memory: "{{ .Values.resources.limits.memory }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      containers:
      - name: {{ .Chart.Name }}-redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            cpu: "{{ .Values.redis.resources.requests.cpu }}"
            memory: "{{ .Values.redis.resources.requests.memory }}"
          limits:
            cpu: "{{ .Values.redis.resources.limits.cpu }}"
            memory: "{{ .Values.redis.resources.limits.memory }}"
